package com.two.dao;

import com.two.pojo.OrderItem;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface OrderItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbggenerated
     */
    int insert(OrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbggenerated
     */
    OrderItem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbggenerated
     */
    List<OrderItem> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OrderItem record);

    int insertBatch(List<OrderItem> orderItemList);


    List<OrderItem> selectByUserId(Integer userId);

    List<OrderItem> selectByUserIdAndOrderNo(@Param("userId") Integer userId,
                                   @Param("orderNo") Long orderNo);

 /*   List<OrderItem> findOrderItemByOrderNo(@Param("userId") Integer userId,
                                             @Param("orderNo") Long orderNo);*/
}