package com.two.dao;

import com.two.pojo.Order;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;
@Mapper
public interface OrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbggenerated
     */
    int insert(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbggenerated
     */
    Order selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbggenerated
     */
    List<Order> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Order record);

    List<Order> selectOrderByUserId(Integer userId);

    List<Order> selectOrderByDetail(@Param("userId") Integer userId,
                                    @Param("orderNo") Long orderNo);

    int deleteOrder(@Param("userId") Integer userId,
                                    @Param("orderNo") Long orderNo);

    Order selectByOrderNo(@Param("orderNo") Long orderNo);

    int updateByOrderNo(Order order);
}