package com.two.dao;

import com.two.pojo.UserInfo;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;
@Mapper
public interface UserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    UserInfo selectUserNamePassword (UserInfo userInfo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    int insert(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    UserInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    List<UserInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserInfo record);

    int selectUserName(UserInfo userInfo);
    UserInfo selectUserNameInfo(UserInfo userInfo);

    UserInfo selectUserCondition(UserInfo userInfo);

    int updatePwd(@Param("username") String userName,@Param("password") String newPassword);

    UserInfo selectUserInfo(@Param("username") String userName,@Param("password") String newPassword);

    int updateUserInfo(UserInfo user);

}